services:
  - type: web
    name: health-service
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGODB_URI
        sync: false
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_CONSUMER_GROUP_ID
        value: health-service-group
      - key: SERVER_PORT
        value: 8080
      - key: GOOGLE_CREDENTIALS_PATH
        sync: false
      - key: GOOGLE_APPLICATION_NAME
        value: early-pulse
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false 