services:
  - type: web
    name: health-service
    runtime: java
    buildCommand: ./gradlew clean build -x test
    startCommand: java -jar build/libs/healthservice-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GOOGLE_CREDENTIALS_PATH
        value: /tmp/google-credentials.json
      - key: GOOGLE_APPLICATION_NAME
        value: early-pulse
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SERVER_PORT
        value: 8080
      - key: SERVER_CONTEXT_PATH
        value: /api
    buildFilter:
      paths:
        - build.gradle
        - src/**
        - gradle/**
        - gradlew
        - gradlew.bat
        - settings.gradle 